#!/usr/bin/env bash
#Displays Best School 10 times, but for the 9th iteration, displays Best School, and then Hi

count=0

while [ $count -lt 11 ]
do
if [ $count -eq 9 ]; then
echo "Hi"
else
echo "Best School"
fi
((count++))
done
