#!/usr/bin/env bash
#Displays numbers from 1 to 20

cnt=1

while [ $cnt -le 20 ]
do
echo "$cnt"
case $cnt in
"4") echo "bad luck from Chine";;
"9") echo "bad luck from Japan";;
"17") echo "bad luck from Italy";;
esac
(( cnt++ ))
done
