#!/usr/bin/env bash
#Displays the time for 12 hours and 59 minutes

time=0

while [ $time -le 12 ]
do
echo "Time: $time"
minute=1
while [ $minute -le 59 ]
do
echo "$minute"
(( minute ++ ))
done
(( time++ ))
done
